### ISSUE TITLE
hi sir 

### ISSUE THREAD

**Issue by pavandraj** [kmhmubin/Face-Recognition-Attendance-System#10]

**Comment by pavandraj** [comment]
> _No description provided._

sir im runnig your code it is showing error "import cv2"
im not getting what is that cv2 module.please help me sir.

**Comment by Rahul218691** [comment]
uninstall the cv2 package installed before and use pip install opencv-contrib-python 
this helped me solve the above issue pls do try this

**Comment by Rahul218691** [comment]
hello Mubin myself Rahul I loved the efforts u have taken to do this project I would like to know how to generate a single CSV file for attendance details for a particular day and also how to add emotion detection to it.

**Comment by pavandraj** [comment]
Hi sir, while installing packages (pip install pytest-shutil) it is showing
error sys.exit(main())
Type error: module object is not callable.
Sir please help me out to debug this issue.


draj
