### ISSUE TITLE
Addons to existing project

### ISSUE THREAD

**Issue by Rahul218691** [kmhmubin/Face-Recognition-Attendance-System#11]
hello, Mubin myself Rahul I loved the efforts u have taken to do this project I would like to know how to generate a single CSV file for attendance details for a particular day and also how to add emotion detection to it.

**Comment by kmhmubin** [comment]
For emotion detection, you need to add new algorithm for face emotion. There is some open source face emotion algorithm out there you need to integrate with the program. As for generating a CSV file, you need to add logic for a specific time which will automatically create a CSV file. Creating CSV file is the same as creating a text file in any programming language.
Thank you Rahul for your suggestion.
