### ISSUE TITLE
hi sir issue related to python-cvs instaling

### ISSUE THREAD

**Issue by pavandraj** [kmhmubin/Face-Recognition-Attendance-System#12]

**Comment by pavandraj** [comment]
sir while installing python-csv im getting error
"Failed building wheel for leven" this is the error im getting.
"Command "C:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\SWATHI\\AppData\\Local\\Temp\\pip-install-wq866pdi\\leven\\setup.py';f=getattr(t
okenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\SWATHI\AppData\Local\Temp\pip-record-
w3z3k12g\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\SWATHI\AppData\Local\Temp\pip-install-wq866pdi\leven\
" getting something like this, sir please help me out.

**Comment by pavandraj** [comment]
while installing  "pytest-shutil" this package im getting "Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\programdata\\anaconda3\\lib\\site-packages\\__pycache__\\zipp.cpython-37.pyc'
Consider using the `--user` option or check the permissions.
" this type error please help me sir.

**Comment by Rahul218691** [comment]
try to run the project creating an environment instead of installing the packages globally
try using pipenv which creates a virtual environment for ur project and u can install ur modules using pipenv install package name

**Comment by kmhmubin** [comment]
try to use pipenv for a virtual environment.
