### ISSUE TITLE
No attendance updation

### ISSUE THREAD

**Issue by mraj16** [kmhmubin/Face-Recognition-Attendance-System#16]
After recognising, it is not updating the data in csv file.

**Comment by Flash2014** [comment]
same issue

**Comment by mraj16** [comment]
Can anyone solve this issue??

**Comment by haithamRD** [comment]
@mraj16 give me your email i send to u the perfect running code

**Comment by bgeffari** [comment]
@haithamRD also I'm interested, can you share the code :)

**Comment by haithamRD** [comment]
get ur email

**Comment by bgeffari** [comment]
bgeffari   at   g mail

**Comment by mraj16** [comment]
mukulraj10@gmail.com

**Comment by kh77** [comment]
kazimhussain77@gmail.com

**Comment by moeez71** [comment]
moeezatlas@hotmail.com 
it recognizes me but the camera stays on and nothing happens

**Comment by kmhmubin** [comment]
You need to manually create the CSV file first. Also, you need to manually close the camera. 
In the future, I will try to improve this project and also add a notification system and automatically create an attendance file.
Thank you for your point.😀

**Comment by moeez71** [comment]
Kindly tell the command to only close the camera. Using the close button it pops up back again and again and does not stop

**Comment by kmhmubin** [comment]
Command to close the camera is: **q**
