### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by moeez71** [kmhmubin/Face-Recognition-Attendance-System#17]
i have installed everything and followed everything but when i try to run the project nothing happens not even an error comes 
py main.py does not do anything
![Screenshot (128)](https://user-images.githubusercontent.com/60314630/77004707-5ff7e280-6981-11ea-93e0-8510e4df012e.png)

**Comment by mraj16** [comment]
try with python3 instead of py.

**Comment by kmhmubin** [comment]
try to open using pycharm and use py3 instead of py

**Comment by moeez71** [comment]
bros can u please help the option 4 is not working for me. Camera recognizes the person but never shuts off and i never get the attendance successful msg
