### ISSUE TITLE
Attendance Problem

### ISSUE THREAD

**Issue by moeez71** [kmhmubin/Face-Recognition-Attendance-System#18]
during the step 4, it recognizes the person, but the camera stays on and nothing happens. Camera stays on recognizing the person and it never says attendance successful.

**Comment by kmhmubin** [comment]
There is no notification system that will alert the attendance taken. You need to manually close the camera. 
In the future, I will try to improve this project and also add a notification system.
Thank you for your point.😀

**Comment by moeez71** [comment]
so u mean the attendance gets added to the csv file in the background, i just have to stop the camera myself. And i can view the updated attendance afterwards? Kindly tell the command to stop the camera. i use Ctrl+C, but it stops the whole program. and i have to restart it all over again

**Comment by kmhmubin** [comment]
after recognizing the person it will automatically add the data in CSV file and the camera closing command is: q

**Comment by moeez71** [comment]
thanks appreciated
