### ISSUE TITLE
Capturing camera opening is too slow

### ISSUE THREAD

**Issue by ganeshchenniah** [kmhmubin/Face-Recognition-Attendance-System#19]
Hi ,

I have faced two issue 
1. Check Camera option opens camera but not closes after close button click
2. Capture image option : camera opening is too slow and movement is not working

**Comment by moeez71** [comment]
issue 1 can be solved. Use q key to close the camera

**Comment by kmhmubin** [comment]
there is no solution for issue 2 for now.
